export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const CLEAR_SHOPPINGCART = "CLEAR_SHOPPINGCART";
export const CREATE_NEW_SHOPPING_CART = "CREATE_NEW_SHOPPING_CART";
export const RETRIEVE_OLD_SHOPPING_CART = "RETRIEVE_OLD_SHOPPING_CART";